name: Deploy Appstore to GitHub Pages

on:
  push:
    branches:
      - master
    paths:
      - 'appstore/**'
      - '.github/workflows/publish-appstore.yml'
  workflow_dispatch:

permissions:
  contents: read
  pages: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload appstore directory as Pages artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./appstore

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1

